
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'


import { Roboto } from 'next/font/google'
import Navbar from '@/components/navbar';
import { ToastContainer } from 'react-toastify';
import UserProvider from '@/context/userProvider';
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} `} suppressHydrationWarning={true}>
        <UserProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </UserProvider>

      </body>

    </html>
  )
}
